/**
 * YouTube Data API v3 Integration
 * Handles API-based channel monitoring (alternative to RSS)
 */

export interface ParsedVideo {
  id: string;
  title: string;
  description?: string;
  publishedAt: string;
  durationSeconds?: number;
  thumbnailUrl?: string;
}

/**
 * Fetch latest videos from YouTube channel using Data API v3
 * Requires YOUTUBE_API_KEY environment variable
 */
export async function fetchYouTubeAPI(
  channelId: string,
  apiKey: string,
  maxResults: number = 50
): Promise<ParsedVideo[]> {
  try {
    // First, get the uploads playlist ID for the channel
    const channelResponse = await fetch(
      `https://www.googleapis.com/youtube/v3/channels?` +
        `part=contentDetails&` +
        `id=${channelId}&` +
        `key=${apiKey}`
    );

    if (!channelResponse.ok) {
      throw new Error(`Failed to fetch channel: ${channelResponse.statusText}`);
    }

    const channelData = (await channelResponse.json()) as any;
    const uploadsPlaylistId =
      channelData.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;

    if (!uploadsPlaylistId) {
      throw new Error(`Could not find uploads playlist for channel ${channelId}`);
    }

    // Fetch videos from the uploads playlist
    const playlistResponse = await fetch(
      `https://www.googleapis.com/youtube/v3/playlistItems?` +
        `part=snippet,contentDetails&` +
        `playlistId=${uploadsPlaylistId}&` +
        `maxResults=${maxResults}&` +
        `key=${apiKey}`
    );

    if (!playlistResponse.ok) {
      throw new Error(`Failed to fetch playlist: ${playlistResponse.statusText}`);
    }

    const playlistData = (await playlistResponse.json()) as any;
    const videoIds = playlistData.items
      ?.map((item: any) => item.contentDetails?.videoId)
      .filter(Boolean);

    if (!videoIds || videoIds.length === 0) {
      return [];
    }

    // Fetch detailed video information
    const videosResponse = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?` +
        `part=snippet,contentDetails&` +
        `id=${videoIds.join(",")}&` +
        `key=${apiKey}`
    );

    if (!videosResponse.ok) {
      throw new Error(`Failed to fetch videos: ${videosResponse.statusText}`);
    }

    const videosData = (await videosResponse.json()) as any;

    // Map to ParsedVideo format
    const videos: ParsedVideo[] = videosData.items
      ?.map((item: any) => {
        const snippet = item.snippet;
        const contentDetails = item.contentDetails;

        return {
          id: item.id,
          title: snippet?.title || "",
          description: snippet?.description,
          publishedAt: snippet?.publishedAt || new Date().toISOString(),
          durationSeconds: parseDuration(contentDetails?.duration),
          thumbnailUrl:
            snippet?.thumbnails?.maxres?.url ||
            snippet?.thumbnails?.high?.url ||
            snippet?.thumbnails?.default?.url,
        };
      })
      .filter((v: ParsedVideo) => v.id && v.title) || [];

    return videos;
  } catch (error) {
    throw new Error(
      `YouTube API fetch failed: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Parse ISO 8601 duration to seconds
 * Example: PT2H30M45S = 9045 seconds
 */
function parseDuration(duration: string): number {
  if (!duration) return 0;

  const match = duration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;

  const hours = parseInt(match[1] || "0");
  const minutes = parseInt(match[2] || "0");
  const seconds = parseInt(match[3] || "0");

  return hours * 3600 + minutes * 60 + seconds;
}

/**
 * Get video statistics (views, likes, comments)
 */
export async function getVideoStats(
  videoId: string,
  apiKey: string
): Promise<{
  views: number;
  likes: number;
  comments: number;
}> {
  try {
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?` +
        `part=statistics&` +
        `id=${videoId}&` +
        `key=${apiKey}`
    );

    if (!response.ok) {
      throw new Error(`Failed to fetch video stats: ${response.statusText}`);
    }

    const data = (await response.json()) as any;
    const stats = data.items?.[0]?.statistics;

    return {
      views: parseInt(stats?.viewCount || "0"),
      likes: parseInt(stats?.likeCount || "0"),
      comments: parseInt(stats?.commentCount || "0"),
    };
  } catch (error) {
    throw new Error(
      `Failed to fetch video statistics: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Get captions/transcript availability
 */
export async function getVideoTranscripts(
  videoId: string,
  apiKey: string
): Promise<
  Array<{
    language: string;
    languageCode: string;
    isAutoGenerated?: boolean;
  }>
> {
  try {
    // Note: Caption tracking requires captions part, but returns only metadata
    // Full transcript retrieval requires YouTube-scrape or separate API
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/captions?` +
        `videoId=${videoId}&` +
        `key=${apiKey}`
    );

    // Captions API may return 403 if not available
    if (!response.ok) {
      return [];
    }

    const data = (await response.json()) as any;
    return (
      data.items?.map((item: any) => ({
        language: item.snippet?.language,
        languageCode: item.id,
        isAutoGenerated: item.snippet?.trackKind === "asr",
      })) || []
    );
  } catch (error) {
    // Gracefully handle caption fetch failures
    return [];
  }
}
